app/beerbattle/controllers.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

# Import flask dependencies
from flask import Blueprint, render_template, request, jsonify, current_app as app

import json

# Import App objects
from app.beerbattle.models import Beer, Battle

# Define a blueprint
beerbattle = Blueprint('beerbattle', __name__, url_prefix='/')

################################################################################
# beerbattle blueprint functions
################################################################################

@beerbattle.route('home', methods=['GET'])
def display():
    app.logger.info('Hit on /home endpoint')
    return render_template('home.html')

@beerbattle.route('catalog', methods=['GET', 'POST'])
def catalog():
    app.logger.info('Hit on /catalog endpoint')
    return render_template('catalog.html', beers=Beer.list_beers())

@beerbattle.route('battle', methods=['GET', 'POST'])
def battle():
    app.logger.info('Hit on /battle endpoint')

    if request.method == 'POST':
        json = request.get_json()

        # Convert a list of dict name= value= into a dict
        json_obj = {}
        model = None

        for j in json:
            json_obj[j['name']] = j['value']

        if 'beer_id_1_win' in json_obj and json_obj['beer_id_1_win'] == 'on':
            model = Battle(json_obj['beer_id_1'], json_obj['beer_id_2'])

        elif 'beer_id_2_win' in json_obj and json_obj['beer_id_2_win'] == 'on':
            model = Battle(json_obj['beer_id_2'], json_obj['beer_id_1'])

        if model:
            model.save()
            return jsonify(result='Battle saved!')
        else:
            return jsonify(result='Something went wrong!')

    else:
        battle_interval = app.config['BEER_BATTLE_ID_INTERVAL'] if 'BEER_BATTLE_ID_INTERVAL' in app.config else None
        beers_for_battle = Beer.get_two_beers(battle_interval=battle_interval)

        return render_template('battles.html', beers=beers_for_battle)

@beerbattle.route('top-beers', methods=['GET'])
def top():
    app.logger.info('Hit on /top-beers endpoint')
    return render_template('top-beers.html', beers=Battle.list_top_beers())

app/templates/battles.html
{% extends "layout.html" %}

{% block title %}
    Beer Battles!
{% endblock %}

{% block head %}
<div class="container text-center">
    <h1>It's Battle Time!</h1>
    <hr />

    <button type="button" class="btn btn-default btn-lg">
        <span class="glyphicon glyphicon-retweet" aria-hidden="true"></span>
        <a href="{{ url_for('beerbattle.battle') }}">Skip battle
        </a>
    </button>

</div>
{% endblock %}

{% block content %}
<div id="battle" class="container">
    <div class="row">

    <form id="vote" method="POST" action="{{ url_for('beerbattle.battle') }}" accept-charset="UTF-8" class="form-horizontal" role="form">
    {% for id, beer in beers.iteritems() %}
        {% if loop.index % 2 == 0 %}
        <div class="col-sm-2 col-md-2 text-center">
            <br /><br /><br /><br />
            <br /><br /><br /><br />
             <span class="glyphicon glyphicon glyphicon-flash battle"></span>
        </div>
        {% endif %}

        <input type="hidden" id="beer_id_{{ loop.index }}" name="beer_id_{{ loop.index }}" value="{{ id }}">

        <div class="col-sm-5 col-md-5">
            <div class="thumbnail">
                <h1 class="text-center">
                    <button type="button" class="btn btn-primary btn-radio"><span class="glyphicon glyphicon-heart-empty"></span>  Vote for {{ beer.name }}</button>
                    <input type="checkbox" id="beer_id_{{ loop.index }}_win" name="beer_id_{{ loop.index }}_win" class="hidden">
                    <br />
                    <br />
                    <img class="img-radio" src="{{ url_for('static', filename='img/beer-' ~ (id % 9 + 1) ~'.png') }}" alt="{{ 'img/beer-' ~ (id % 9) + 1 ~'.png' }}">
                </h1>

                <div class="caption">
                    <h4>{{ beer.name }}</h4>
                    <hr />
                    <p>
                        <span class="glyphicon glyphicon glyphicon-grain"></span> {{ beer.brewery }}<br />
                        <span class="glyphicon glyphicon glyphicon-glass"></span> Vol. {{ beer.abv }} %<br />
                        <span class="glyphicon glyphicon glyphicon-tag"></span>
                        {% for type in beer.type.split(',') %}
                            {% if "blonde" in type | lower %}
                                <span class="label label-info">{{ type }}</span>
                            {% elif "brune" in type | lower() %}
                                <span class="label label-warning">{{ type }}</span>
                            {% elif "triple" in type | lower() %}
                                <span class="label label-success">{{ type }}</span>
                            {% elif "fruitée" in type | lower() or "noël" in type | lower() %}
                                <span class="label label-danger">{{ type }}</span>
                            {% else %}
                                <span class="label label-default">{{ type }}</span>
                            {% endif %}
                        {% endfor %}
                        <br />
                        <hr />
                    </p>
                </div>
            </div>
        </div>
    {% endfor %}

    </form>

    </div>
</div>
{% endblock %}

{% block javascript %}
    {{ super() }}

    <script type="text/javascript">
        $(function () {
            $(document).ready(function () {
                $("#vote").hide();
                $("#vote").slideDown(400);
            });

            $('.btn-radio').click(function(e) {
                $('.btn-radio').not(this).removeClass('active')
                    .siblings('input').prop('checked',false)
                    .siblings('.img-radio').css('opacity','0');

                $(this).addClass('active')
                    .siblings('input').prop('checked',true)
                    .siblings('.img-radio').css('opacity','1');

                var formData = JSON.stringify($("#vote").serializeArray());

                // console.log(formData);

                $.ajax({
                    type: "POST",
                    url: $SCRIPT_ROOT + "{{ url_for('beerbattle.battle') }}",
                    data: formData,
                    success: function(){
                        $("#vote").slideUp(400, 'swing', function() {
                            location.reload();
                        });
                    },
                    dataType: "json",
                    contentType : "application/json"
                });
            });
        });
    </script>

{% endblock %}

app/templates/catalog.html
{% extends "layout.html" %}

{% block title %}
    Beer Catalog
{% endblock %}

{% block head %}
{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        {% for index, beer in beers.iteritems() %}
        <div class="col-sm-4 col-md-4">
            <div class="thumbnail">
                <img src="{{ url_for('static', filename='img/beer-' ~ (loop.index0 % 9 + 1) ~'.png') }}" alt="{{ 'img/beer-' ~ (loop.index0 % 9) + 1 ~'.png' }}">

                <div class="caption">
                    <h4>{{ beer.name }}</h4>
                    <hr />
                    <p>
                        <span class="glyphicon glyphicon glyphicon-grain"></span> {{ beer.brewery }}<br />
                        <span class="glyphicon glyphicon glyphicon-glass"></span> Vol. {{ beer.abv }} %<br />
                        <span class="glyphicon glyphicon glyphicon-tag"></span>
                        {% for type in beer.type.split(',') %}
                            {% if "blonde" in type | lower %}
                                <span class="label label-info">{{ type }}</span>
                            {% elif "brune" in type | lower() %}
                                <span class="label label-warning">{{ type }}</span>
                            {% elif "triple" in type | lower() %}
                                <span class="label label-success">{{ type }}</span>
                            {% elif "fruitée" in type | lower() or "noël" in type | lower() %}
                                <span class="label label-danger">{{ type }}</span>
                            {% else %}
                                <span class="label label-default">{{ type }}</span>
                            {% endif %}
                        {% endfor %}
                    </p>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

app/templates/error.html
{% extends "layout.html" %}

{% block title %}
    Error!
{% endblock %}

{% block head %}
{% endblock %}

{% block content %}
<div class="container">
    <div class="jumbotron">
        <h1><span class="glyphicon glyphicon-fire"></span> Something went wrong...</h1>
        <blockquote>
            <p><code>{{ error }}</code></p>
        </blockquote>
        <p><a class="btn btn-primary btn-lg" href="{{ url_for('beerbattle.display') }}" role="button">Let's go back inside</a></p>
    </div>
</div>

{% endblock %}

app/templates/footer.html
<!-- Footer -->
<footer>
    <div class="container">
        <div class="row">
            <div class="col-lg-6 text-center">
                <ul class="list-inline">
                    <li>
                        <a href="{{ url_for('beerbattle.display') }}">Home</a>
                    </li>
                    <li class="footer-menu-divider">&sdot;</li>
                    <li>
                        <a href="{{ url_for('beerbattle.catalog') }}">Catalog</a>
                    </li>
                    <li class="footer-menu-divider">&sdot;</li>
                    <li>
                        <a href="{{ url_for('beerbattle.top') }}">Top Beers</a>
                    </li>
                    <li class="footer-menu-divider">&sdot;</li>
                    <li>
                        <a href="{{ url_for('beerbattle.battle') }}">Battles</a>
                    </li>
                </ul>
            </div>
            <div class="col-lg-6 text-center">
                <p class="text-muted small">DevOps 360° - INSSET 2017 - Florian Dambrine</p>
            </div>
            <div class="col-lg-12 text-center">
                <small><p>Icon made by <a target="blank" title="Freepik" href="http://www.freepik.com">Freepik</a> from <a target="blank" title="Flaticon" href="http://www.flaticon.com">www.flaticon.com</a>&nbsp;</p></small>
            </div>

        </div>
    </div>
</footer>

app/templates/header.html
<!-- Navigation -->
<nav class="navbar navbar-default navbar-fixed-top topnav" role="navigation">
    <div class="container topnav">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand topnav" href="#">Beer <span class="glyphicon glyphicon-flash"></span> Battle</a>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a href="{{ url_for('beerbattle.display') }}">Home</a>
                </li>
                <li>
                    <a href="{{ url_for('beerbattle.catalog') }}">Catalog</a>
                </li>
                <li>
                    <a href="{{ url_for('beerbattle.top') }}">Top Beers</a>
                </li>
                <li>
                    <a href="{{ url_for('beerbattle.battle') }}">Battles</a>
                </li>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
</nav>

<!-- Header -->
<div class="container bartender">
        <div>
            <img class="img-responsive pull-right" width="10%" height="10%" src="{{ url_for('static', filename='img/bartender.png') }}" alt="">
            <div class="panel panel-default pull-right">
                <div class="panel-body text-right">
                    <p>
                        You are being served by : <span class="label label-primary">{{ get_server_name() | default('-') }}</span>
                    </p>
                    <p>
                        Backend: <span class="label {% if get_db_connection_state() %}label-success{% else %}label-danger{% endif %}">
                            {% if get_db_connection_state() %}
                                <span class="glyphicon glyphicon-resize-small"></span>
                            {% else %}
                                <span class="glyphicon glyphicon-resize-full"></span>
                            {% endif %}
                            {{ get_db_connection_string() | default('-') }}
                        </span>

                    </p>

                    <p>
                        Code revision is : <span class="label label-primary">{{ get_git_revision() | default('-') }}</span>
                        <span class="label label-primary">{{ get_git_tag() | default('-') }}</span>
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>

app/templates/home.html
{% extends "layout.html" %}

{% block head %}
    <div class="intro-header">
        <div class="container">
            <!-- <span>Icon made by <a title="Freepik" href="http://www.freepik.com">Freepik</a> from <a title="Flaticon" href="http://www.flaticon.com">www.flaticon.com</a>&nbsp;</span> -->

            <!-- <a href="http://www.freepik.com/free-photos-vectors/icon">Icon vector created by Freepik</a> -->
            <div class="row">
                <div class="col-lg-12">
                    <div class="intro-message">
                        <h1>Beer <span class="glyphicon glyphicon-flash battle"></span> Battle</h1>
                        <hr class="intro-divider">
                        <h3>The only one who knows which one is your favorite...</h3>
                        <hr class="intro-divider">

                        <button type="button" class="btn btn-default btn-lg">
                            <span class="glyphicon glyphicon-heart-empty" aria-hidden="true"></span>
                            <a href="{{ url_for('beerbattle.top') }}"> Checkout top beers
                            </a>
                        </button>
                        or
                        <button type="button" class="btn btn-default btn-lg">
                            <span class="glyphicon glyphicon-flash" aria-hidden="true"></span>
                            <a href="{{ url_for('beerbattle.battle') }}">Start a new battle
                            </a>
                        </button>

                    </div>
                </div>
            </div>

        </div>
        <!-- /.container -->
    </div>
    <!-- /.intro-header -->
{% endblock %}

{% block content %}
    <!-- Page Content -->
    <div class="content-section-odd">

        <div class="container">
            <div class="row">
                <div class="col-lg-6 col-sm-8">
                    <div class="clearfix"></div>
                    <br />
                    <h2 class="section-heading">❤ Made for beer lovers</h2>
                    <p class="lead">
                        <blockquote>
                            <small>
                                This application allows you to rate thousand of belgium beers.

                                <br /><br />

                                The database comes from the <a href="https://fr.wikipedia.org/wiki/Liste_des_bi%C3%A8res_belges" target="blank">Wikipedia page named "Liste des bières belges"</a>

                                <br /><br />
                                <i class="text-justify">
                                This list summarizes belgium beers, ordered by alphabetic letter. End 2011, we count about 1 150 belgium beers, brewed and commercialized by 146 breweries and 44 malting companies.
                                </i>
                            </small>
                        </blockquote>
                    </p>
                </div>

                <div class="col-lg-5 col-lg-offset-1 col-sm-4">
                    <hr class="section-heading-spacer-invisible">
                    <div class="clearfix"></div>
                    <img class="img-responsive" src="{{ url_for('static', filename='img/beer-lovers.png') }}" alt="">
                </div>
            </div>

        </div>
    </div>

	<a  name="contact"></a>
    <div class="banner">

        <div class="container">

            <div class="row">
                <div class="col-lg-5">
                    <a href="{{ url_for('beerbattle.battle') }}" style="color: white;">
                        <h2 class="text-left">Ready to vote for your favorite one ?</h2>
                    </a>
                </div>
                <div class="col-lg-3">
                    <div class="well stars">
                        Triple Karmeliet:
                        <span class="glyphicon glyphicon-star"></span>
                        <span class="glyphicon glyphicon-star"></span>
                        <span class="glyphicon glyphicon-star"></span>
                        <span class="glyphicon glyphicon-star-empty"></span>
                        <span class="glyphicon glyphicon-star-empty"></span>
                    </div>
                </div>

                <div class="col-lg-1">
                    <p class="text-center"><span class="glyphicon glyphicon-flash battle"></span></p>
                </div>

                <div class="col-lg-3">
                    <div class="well stars">
                        Delirium Tremens:
                        <span class="glyphicon glyphicon-star"></span>
                        <span class="glyphicon glyphicon-star"></span>
                        <span class="glyphicon glyphicon-star-empty"></span>
                        <span class="glyphicon glyphicon-star-empty"></span>
                        <span class="glyphicon glyphicon-star-empty"></span>
                    </div>
                </div>

            </div>

        </div>
        <!-- /.container -->

    </div>
    <!-- /.banner -->
{% endblock %}

app/templates/layout.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% block title %}Beer Battle{% endblock %}</title>

    <link rel="shortcut icon" href="{{ url_for('static', filename='img/favicon.ico') }}">
    <!-- Bootstrap Core CSS -->
    <link href="{{ url_for('static', filename='css/bootstrap.min.css') }}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{{ url_for('static', filename='css/landing-page.css') }}" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="{{ url_for('static', filename='font-awesome/css/font-awesome.min.css') }}" rel="stylesheet" type="text/css">
    <link href="{{ url_for('static', filename='google/lato.css') }}" rel="stylesheet" type="text/css">
    <!-- <link href="http://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">-->

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

    {# Jquery/Flask Setup #}
    <script type=text/javascript>
        $SCRIPT_ROOT = {{ request.script_root|tojson|safe }};
    </script>

</head>

<body>
    {% block header %}
        {% include 'header.html' %}
    {% endblock %}

    {% block head %}
    {% endblock %}

    {% block content %}
    {% endblock %}

    {% include 'footer.html' %}

    {% block javascript %}
        <!-- jQuery -->
        <script src="{{ url_for('static', filename='js/jquery.js') }}"></script>

        <!-- Bootstrap Core JavaScript -->
        <script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
    {% endblock %}
</body>

</html>

app/templates/top-beers.html
{% extends "layout.html" %}

{% block title %}
    Top Beers
{% endblock %}

{% block head %}
{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        {% for index, beer in beers.iteritems() %}
        {% if loop.first %}
            {% set block_css = 'col-sm-12 col-md-12' %}
        {% else %}
            {% set block_css = 'col-sm-4 col-md-4' %}
        {% endif %}
        <div class="{{ block_css }}">
            <div class="thumbnail">
                <h1><span class="glyphicon glyphicon-{% if loop.first %}heart{% else %}heart-empty{% endif %}"></span> {{ beer.rate }}</h1>

                <img src="{{ url_for('static', filename='img/beer-' ~ (loop.index0 % 9 + 1) ~'.png') }}" alt="{{ 'img/beer-' ~ (loop.index0 % 9) + 1 ~'.png' }}">

                <div class="caption">
                    <h4>{{ beer.beer_win.name }}</h4>
                    <hr />
                    <p>
                        <span class="glyphicon glyphicon glyphicon-bookmark"></span> Classement: {{ loop.index }}/{{ beers | length }}<br />
                        <span class="glyphicon glyphicon glyphicon-grain"></span> {{ beer.beer_win.brewery }}<br />
                        <span class="glyphicon glyphicon glyphicon-glass"></span> Vol. {{ beer.beer_win.abv }} %<br />
                        <span class="glyphicon glyphicon glyphicon-tag"></span>
                        {% for type in beer.beer_win.type.split(',') %}
                            {% if "blonde" in type | lower %}
                                <span class="label label-info">{{ type }}</span>
                            {% elif "brune" in type | lower() %}
                                <span class="label label-warning">{{ type }}</span>
                            {% elif "triple" in type | lower() %}
                                <span class="label label-success">{{ type }}</span>
                            {% elif "fruitée" in type | lower() or "noël" in type | lower() %}
                                <span class="label label-danger">{{ type }}</span>
                            {% else %}
                                <span class="label label-default">{{ type }}</span>
                            {% endif %}
                        {% endfor %}
                    </p>
                </div>
            </div>
         </div>
        {% endfor %}
    </div>
</div>
{% endblock %}